Tentative extract token
BladeBuru/API-mangaTracker pull request #17
Opened 2023-06-21 21:43 UTC by suprasanity

2023-06-21 21:46 UTC, suprasanity commented
Please take a look at the updated endpoint and tell me what do you think about the solution I came up with

2023-07-10 17:53 UTC, williammadie requested changes
I saw that there is a possibility of creating a custom decorator @User which might be a good enhancement of what you've done (see full example here : https://docs.nestjs.com/custom-decorators)

I think the following tasks would be to :

- create the custom decorator @User
- add this decorator to endpoints currently taking a userId in parameter inside a DTO. 
- remove the old userId from the DTOs but keep these DTO (don't switch to @parameter even if there is a single attribute inside the DTO)

2023-07-11 18:39 UTC, williammadie commented on src/api/library/library.controller.ts
Fix deletion of chapter update endpoint

2023-07-11 18:48 UTC, williammadie requested changes
Fix deletion of chapter update endpoint

2023-07-11 19:56 UTC, suprasanity commented
should be fine by now

2023-07-11 20:25 UTC, williammadie approved these changes

2023-07-11 20:25 UTC, merged